/* txtserve.h */

/* Send text to clients generated by the parser */

#ifndef TXTSERVE_H

#define TXTSERVE_H 1

#include "wstypes.h"

void *
txtserve_build(wsstruct *wd, int *len) ;

int
txtserve_tx(wsstruct *wd) ;

#endif
